services:
  init:
    build: ./init
    volumes:
      - datadir:/data
      - status:/status
    environment:
      - SNAPSHOT_URL=${SNAPSHOT_URL:-https://constellationlabs-dashboard-beta.s3.amazonaws.com/intuition-03-11-2026.tar.gz}
      - OFFICIAL_RPC=https://rpc.intuition.systems/http
      - NITRO_RPC=http://nitro:8545
    restart: unless-stopped

  nitro:
    build:
      context: .
      dockerfile: nitro/Dockerfile
    platform: linux/amd64
    volumes:
      - datadir:/home/user/.arbitrum
    entrypoint:
      - /usr/local/bin/nitro
      - --conf.file=/config/nodeConfig.json
      - --node.staker.enable
      - --node.staker.strategy=Watchtower
      - --execution.forwarding-target=wss://rpc.intuition.systems/ws
      - --node.feed.input.url=wss://rpc.intuition.systems/feed
      - --parent-chain.connection.url=${BASE_RPC_URL}
      - --node.dangerous.disable-blob-reader
      - --node.data-availability.rest-aggregator.urls=https://rpc.intuition.systems/rest-aggregator
      - --node.data-availability.parent-chain-node-url=${BASE_RPC_URL}
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    expose:
      - "80"
    networks:
      - default
      - coolify
    restart: unless-stopped

volumes:
  datadir:
  status:

networks:
  coolify:
    external: true
